### ISSUE TITLE
Doesn't work on my computer :(

### ISSUE THREAD

**Issue by ncasaril** [lohmega/jamble#1]
- One recently powercycled blueberry within close range
- Cycled hci0 as well, no change (```sudo hciconfig hci0 down;sudo hciconfig hci0 up```)
- Do the ```"Trusted": False``` below matter?

```
python3 cliapp.py fetch -a 0 --verbose
DEBUG: Namespace(_actionFunc=<function doFetch at 0x7fa6eab7fd08>, address='0', file=None, fmt='txt', help=False, num=None, rtd=False, verbose=1)
DEBUG: ----- VERSIONS ----
 {'bluez': 'bluetoothctl: 5.49',
 'dbus': '1.2.0',
 'os': 'Linux-4.4.0-146-generic-x86_64-with-Ubuntu-16.04-xenial',
 'python': '3.5.2'}
DEBUG: ----- DEVICE ----
 {   'Adapter': '/org/bluez/hci0',
    'Address': 'F9:85:F4:F3:87:75',
    'AddressType': 'random',
    'Alias': 'BlueBerry',
    'Blocked': False,
    'Connected': True,
    'LegacyPairing': False,
    'Name': 'BlueBerry',
    'Paired': False,
    'ServicesResolved': True,
    'Trusted': False,
    'UUIDs': [   '00001800-0000-1000-8000-00805f9b34fb',
                 '00001801-0000-1000-8000-00805f9b34fb',
                 '0000180a-0000-1000-8000-00805f9b34fb',
                 '0000180f-0000-1000-8000-00805f9b34fb',
                 'c9f60002-9f9b-fba4-5847-7fd701bf59f2']}
DEBUG: ----- DEVICE ----
 {   'Adapter': '/org/bluez/hci0',
    'Address': '6C:94:F8:D4:4F:1C',
    'AddressType': 'public',
    'Alias': '6C-94-F8-D4-4F-1C',
    'Blocked': False,
    'Connected': False,
    'LegacyPairing': False,
    'ManufacturerData': {   dbus.UInt16(76): [   dbus.Byte(9),
                                                 dbus.Byte(6),
                                                 dbus.Byte(3),
                                                 dbus.Byte(19),
                                                 dbus.Byte(192),
                                                 dbus.Byte(168),
                                                 dbus.Byte(10),
                                                 dbus.Byte(193)]},
    'Paired': False,
    'ServicesResolved': False,
    'Trusted': False,
    'UUIDs': []}
DEBUG: ----- DEVICE ----
 {   'Adapter': '/org/bluez/hci0',
    'Address': '80:7A:BF:13:12:C4',
    'AddressType': 'public',
    'Alias': 'HTC BS C4EB55',
    'Blocked': False,
    'Connected': False,
    'LegacyPairing': False,
    'Name': 'HTC BS C4EB55',
    'Paired': False,
    'ServicesResolved': False,
    'Trusted': False,
    'UUIDs': ['0000cb00-0000-1000-8000-00805f9b34fb']}
DEBUG: ----- DEVICE ----
 {   'Adapter': '/org/bluez/hci0',
    'Address': 'F3:CF:2D:4D:8E:EC',
    'AddressType': 'random',
    'Alias': 'ncb_Node-CFB20492',
    'Blocked': False,
    'Connected': False,
    'LegacyPairing': False,
    'Name': 'ncb_Node-CFB20492',
    'Paired': False,
    'ServicesResolved': False,
    'Trusted': False,
    'UUIDs': ['00001811-0000-1000-8000-00805f9b34fb']}
DEBUG: ----- DEVICE ----
 {   'Adapter': '/org/bluez/hci0',
    'Address': '80:7A:BF:13:12:65',
    'AddressType': 'public',
    'Alias': 'HTC BS 656870',
    'Blocked': False,
    'Connected': False,
    'LegacyPairing': False,
    'Name': 'HTC BS 656870',
    'Paired': False,
    'ServicesResolved': False,
    'Trusted': False,
    'UUIDs': ['0000cb00-0000-1000-8000-00805f9b34fb']}
DEBUG: ----- DEVICE ----
 {   'Adapter': '/org/bluez/hci0',
    'Address': 'E9:11:B4:D7:CB:8A',
    'AddressType': 'random',
    'Alias': 'listener-48E2C12A',
    'Blocked': False,
    'Connected': False,
    'LegacyPairing': False,
    'Name': 'listener-48E2C12A',
    'Paired': False,
    'ServicesResolved': False,
    'Trusted': False,
    'UUIDs': ['00001811-0000-1000-8000-00805f9b34fb']}
DEBUG: ----- DEVICE ----
 {   'Adapter': '/org/bluez/hci0',
    'Address': '48:D7:05:DC:B7:F8',
    'AddressType': 'public',
    'Alias': '48-D7-05-DC-B7-F8',
    'Blocked': False,
    'Connected': False,
    'LegacyPairing': False,
    'ManufacturerData': {   dbus.UInt16(76): [   dbus.Byte(16),
                                                 dbus.Byte(5),
                                                 dbus.Byte(7),
                                                 dbus.Byte(28),
                                                 dbus.Byte(75),
                                                 dbus.Byte(180),
                                                 dbus.Byte(159)]},
    'Paired': False,
    'ServicesResolved': False,
    'Trusted': False,
    'UUIDs': []}
DEBUG: ----- DEVICE ----
 {   'Adapter': '/org/bluez/hci0',
    'Address': '6E:A2:71:E7:04:D5',
    'AddressType': 'random',
    'Alias': '6E-A2-71-E7-04-D5',
    'Blocked': False,
    'Connected': False,
    'LegacyPairing': False,
    'ManufacturerData': {   dbus.UInt16(76): [   dbus.Byte(16),
                                                 dbus.Byte(5),
                                                 dbus.Byte(26),
                                                 dbus.Byte(28),
                                                 dbus.Byte(103),
                                                 dbus.Byte(189),
                                                 dbus.Byte(72)]},
    'Paired': False,
    'ServicesResolved': False,
    'Trusted': False,
    'UUIDs': []}
Using: F9:85:F4:F3:87:75 BlueBerry
DEBUG: logEP {'Flags': ['notify'],
 'NotifyAcquired': False,
 'Notifying': False,
 'Service': '/org/bluez/hci0/dev_F9_85_F4_F3_87_75/service000e',
 'UUID': 'c9f60021-9f9b-fba4-5847-7fd701bf59f2',
 'Value': []}
Traceback (most recent call last):
  File "/home/niklas/git/loligo/jamble/bblogger/bluetoothle/ble_linux.py", line 384, in _get
    return self._queue.get(block=True, timeout=timeout)
  File "/usr/lib/python3.5/queue.py", line 172, in get
    raise Empty
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cliapp.py", line 280, in <module>
    main()
  File "cliapp.py", line 276, in main
    args._actionFunc(args)
  File "cliapp.py", line 129, in doFetch
    ofile=ofile)
  File "/home/niklas/git/loligo/jamble/bblogger/bblogger.py", line 482, in fetch
    chunk = pbdata.read(timeout=10)
  File "/home/niklas/git/loligo/jamble/bblogger/bluetoothle/ble_linux.py", line 434, in read
    return self._get(timeout)
  File "/home/niklas/git/loligo/jamble/bblogger/bluetoothle/ble_linux.py", line 387, in _get
    raise TimeoutError('Read notfications timeout')
TimeoutError: Read notfications timeout
```

```
hciconfig 
hci0:	Type: Primary  Bus: USB
	BD Address: AC:FD:CE:54:4D:C6  ACL MTU: 1021:5  SCO MTU: 96:6
	UP RUNNING 
	RX bytes:16022 acl:93 sco:0 events:760 errors:0
	TX bytes:7228 acl:93 sco:0 commands:273 errors:0
```

**Comment by 5frank** [comment]
please reopen or make a new issue if problem(s) not resolved.
